sudo: required
osx_image: xcode7.1
language: swift

before_install:

    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:

    - pod lib lint

    - xctool -project SwiftDate.xcodeproj -scheme 'SwiftDate'